include:
  - '/.gitlab-ci/.before-script-template.yml'
  - '/.gitlab-ci/.feature-build.yml' # handles any feature/* branch commits
  - '/.gitlab-ci/.merge-build.yml' # handles any merge commits

stages:
  - build
  - documentation
  - deploy

image: python:3.9
