build::pypi:
  stage: build
  environment: staging
  script:
    - python ./setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${TWINE_API_TOKEN} TWINE_USERNAME=__token__ python -m twine upload --repository testpypi dist/*  
  artifacts:
    name: "${CI_COMMIT_BRANCH}-${CI_ENVIRONMENT_NAME}"
    paths:
      - dist/*.whl
      - dist/*.gz
    expire_in: 15 minutes
  only:
    - merge_requests

doc::sphinx:
  stage: documentation
  environment: staging
  dependencies:
    - build::pypi
  script:
    - pip install sphinx recommonmark sphinx_rtd_theme
    - sphinx-build -M html ./docs documentation
  artifacts:
    name: "${CI_COMMIT_BRANCH}-${CI_ENVIRONMENT_NAME}-docs"
    paths:
      - documentation/*
    expire_in: 15 minutes
  only:
    - merge_requests