build::pypi:
  stage: build
  script:
    - python ./setup.py sdist bdist_wheel
    - pip install twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*  
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.gz
    expire_in: 15 minutes
  only:
    - tags
  except:
    - branches

doc::sphinx:
  stage: documentation
  needs:
    - build::pypi
  script:
    - pip install sphinx recommonmark sphinx_rtd_theme
    - sphinx-build -M html ./docs documentation
  artifacts:
    paths:
      - documentation/*
    expire_in: 15 minutes
  only:
    - tags
  except:
    - branches

deploy::pypi:
  stage: deploy
  needs:
    - job: build::pypi
      artifacts: true
  dependencies:
    - build::pypi
  script:
    - echo "This job deploys something quickly."
  only:
    - tags
  except:
    - branches

deploy::pypi::documentation:
  stage: deploy
  needs:
    - job: build::pypi
      artifacts: true
    - job: doc::sphinx
      artifacts: true
  dependencies:
    - build::pypi
    - doc::sphinx
  script:
    - echo "This job deploys documentation quickly."
  only:
    - tags
  except:
    - branches